/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": []
}
}
export {};

import routeFn from 'ziggy-js';

declare global {
    let route: typeof routeFn;
}
